name: taskist
description: Task List App

version: 1.0.0+6

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_analytics: ^5.0.11
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5

  font_awesome_flutter: ^8.0.1

  flutter_colorpicker: ^0.2.2
  flutter_slidable: ^0.4.9

  url_launcher: ^5.0.2
  share: ^0.6.0+1
  launch_review: ^2.0.0

  modal_progress_hud: ^0.1.3

  connectivity: ^0.4.2

  charts_flutter: ^0.9.0
  google_fonts: ^0.4.0
  outline_material_icons: ^0.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/list.png
